import matplotlib.pyplot as plt
import numpy as np
from scipy.ndimage import gaussian_filter1d
output_path = "/home/ben/Desktop/openSCAD/whooshy_shape.scad"
# === Configuration ===
inches = 8;
mm = inches * 25.4;
R=mm/2;

num_points = 2500
base_radius = R - 15

max_deviation = 50  # how much the radius can expand/shrink
smoothness = 25    # higher = smoother, whooshier curves

# === Generate angle values ===
theta = np.linspace(0, 2 * np.pi, num_points)

# === Raw noise ===
raw_noise = np.random.uniform(-1, 1, num_points)

# === Smooth the noise to make big curves ===
smooth_noise = gaussian_filter1d(raw_noise, sigma=smoothness)

# === Modulate radius ===
r = base_radius + max_deviation * smooth_noise

# === Convert to Cartesian ===
x = r * np.cos(theta)
y = r * np.sin(theta)

# === Plot ===
with open(output_path, "w") as f:
    f.write("// Whooshy shape generated by Python\n")
    f.write("module whooshes() {\n")
    f.write("polygon(points=[\n")
    for i in range(num_points):
        if(i < num_points - 1):
            f.write(f"  [{x[i]:.4f}, {y[i]:.4f}],\n")
        else:
            f.write(f"  [{x[i]:.4f}, {y[i]:.4f}]\n")
    f.write("]);\n")
    f.write("};\n")

print(f"Shape written to: {output_path}")
plt.figure(figsize=(6,6))
plt.plot(x, y, color='crimson')
plt.grid(True, linestyle='--', alpha=0.4)
plt.gca().set_aspect('equal')
plt.gca().set_axisbelow(True)
plt.title("Whooshy Organic Circle")
plt.xlabel("X")
plt.ylabel("Y")
plt.show()
